# Generated by Django 4.1.3 on 2023-03-12 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('tenants', '0001_initial'),
        ('landlords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='property',
            field=models.ManyToManyField(blank=True, null=True, related_name='property', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, related_name='tenant', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
