# Generated by Django 4.1.3 on 2023-03-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('HOUSE', 'house'), ('APARTMENT', 'apartment')], default='HOUSE', max_length=9)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('prop_images', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ON REVIEW', 'on review'), ('OPEN', 'open'), ('ON HOLD', 'on hold'), ('BOOKED', 'booked')], default='ON REVIEW', max_length=9)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to='landlords.propertyowner')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_starts', models.DateTimeField()),
                ('contract_ends', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('WEEKLY', 'weekly'), ('BIWEEKELY', 'biweekely'), ('MONTHLY', 'monthly'), ('ANNUALLY', 'annually')], default='MONTHLY', max_length=20)),
                ('payment_amount', models.FloatField()),
                ('contract_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='landlords.propertyowner')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
