# Generated by Django 4.1.3 on 2023-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('invoice_amount', models.CharField(max_length=200)),
                ('notification_status', models.CharField(choices=[('SENT', 'sent'), ('PAID', 'paid')], default='ON REVIEW', max_length=9)),
                ('invoice_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
