# Generated by Django 4.1.3 on 2023-03-12 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('LANDLORD', 'landlord'), ('TENANT', 'tenant')], default='TENANT', max_length=8)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('contact_number', models.IntegerField(default=0, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('is_firsttimelogin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 14, 8, 20, 277701))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 3, 12, 14, 8, 20, 277701))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
